---
{{ if not .Values.config.secret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "nodepool.fullname" . }}
  labels:
{{- include "nodepool.common.labels" . | indent 4 }}
stringData:
  nodepool.yaml: |
{{ toYaml .Values.config | indent 4 }}
  clouds.yaml: |
    clouds:
{{ toYaml .Values.clouds | indent 6 }}
{{ end }}